a

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,9 +1,5 @@
 name: Building # Nombre del workflow
 on: [push]
-#  push:
-#    tags:
-#      - "v*.*.*" # Este on solo se ejecuta cuando hay etiqueta
-
 jobs: # Solo vamos a crear uno
   building:
     runs-on: ubuntu-latest
@@ -18,46 +14,13 @@ jobs: # Solo vamos a crear uno
         run: poetry install
       - name: Testing
         run: poetry run pytest --junitxml=jest-junit.xml --cov=modeltools --cov-report=lcov --cov-report=xml
-      - uses: actions/upload-artifact@v2  # upload test results
-        if: success() || failure()        # run this step even if previous step failed
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
         with:
-          name: test-results
-          path: jest-junit.xml
-      - uses: dorny/test-reporter@v1
-        with:
-          path: jest-junit.xml
-          #artifact: test-results            # artifact name
-          name: JEST Tests                  # Name of the check run which will be created
-          #path: '*.xml'                     # Path to test results (inside artifact .zip)
-          reporter: java-junit              # Format of test results
-#      - uses: romeovs/lcov-reporter-action@v0.2.16
-#        with:
-#          lcov-file: coverage.lcov
-      - name: Code Coverage Report
-        uses: irongut/CodeCoverageSummary@v1.3.0
-        with:
-          filename: coverage*.xml
-          badge: true
-          fail_below_min: true
-          format: markdown
-          hide_branch_rate: false
-          hide_complexity: true
-          indicators: true
-          output: both
-          thresholds: '60 80'
-      
-      - uses: devmasx/coverage-check-action@v1.2.0
-        with:
-          type: lcov
-          result_path: coverage.lcov
-          min_coverage: 90
-          token: ${{ github.token }}
-      - name: Add Coverage PR Comment
-        uses: marocchino/sticky-pull-request-comment@v2
-        with:
-          recreate: true
-          path: code-coverage-results.md
-      - run: poetry build # Ejecuto un comando de consola en el repo.
+          name: Test            # Name of the check run which will be created
+          path: jest-junit.xml    # Path to test results
+          reporter: jest-junit        # Format of test results
       - name: Publish to GH Releases
         if: startsWith(github.ref, 'refs/tags/v')
         uses: softprops/action-gh-release@v1
